import KeyMirror from 'keymirror'

const ActionTypes = new KeyMirror({
  ALERTS_ON: null,
  ALERTS_OFF: null,
  FREQUENCY: null,
  CONTENT_INFO: null,
  CHANGE_DATE: null,
  START_SPINNER: null,
  STOP_SPINNER: null,
  PROFILE_INFO: null,
  SHOW_MODAL: null,
  HIDE_MODAL: null,
  RECORDS: null,
  IS_TAG: null,
  THEME: null,
  IMAGE_EXPAND: null,
  IMAGE_CHANGE: null,
  READ_THOUGHT: null,
  READ_STORY: null,
  CHANGE_VIDEO: null,
  CHANGE_AUDIO: null,
  ON_NOTIFICATION: null,
  PLAY_AUDIO: null,
  LONGPRESS_DETECTED: null,
  LONGPRESS_DETECTED1: null,
  LONGPRESS_DETECTED2: null,
  LONGPRESS_DETECTED3: null,
  LONGPRESS_DETECTED4: null,
  LONGPRESS_DETECTED5: null,
  LONGPRESS_DETECTED6: null,
  LONGPRESS_DETECTED7: null,
  LONGPRESS_DETECTED8: null,
  LONGPRESS_DETECTED9: null,
  ADD_IMAGE: null,
  IS_CALENDAR: null,
  ALL_DATES: null,
  APP_CONSTANTS: null,
  IS_ENGLISH_THOUGHT: null,
  IS_ENGLISH_STORY: null,
  IS_REACH: null,
  CHANNEL_INFO: null,
  SEL_CHANNELS: null,
  UNSEL_CHANNELS: null,
  DISABLED_CHANNELS: null,
  CHANNEL_CHANGE: null,
  NOTIF_DATE: null,
  SHARE_IMAGE: null,
  IS_SEARCH: null,
  TAG_VALUE: null,
  IS_RECORDS: null,
  RECORDS_EXISTS: null,
  ROWS_DISPLAYED: null,
  INTERNET_ALERT: null,
  RECORDS_RENDERED: null,
  SEARCH_CLICK: null,
})

Object.freeze(ActionTypes)

export default ActionTypes
